name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: node --version; python --version
      - run: npm ci
      - run: npm run publish -- --dry-run
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_KEY_ID: ${{ secrets.FIREBASE_KEY_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GH_ISSUES_CLIENT_ID: ${{ secrets.GH_ISSUES_CLIENT_ID }}
      - run: npm run publish -- --from-dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
