name: Release

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: choco install python visualstudio2022-workload-vctools -y
      - run: python3 --version
